### ISSUE TITLE
Change constants.py to another location

### ISSUE THREAD

**Issue by t-cheepeng** [t-cheepeng/time-tracker-visualizer#2]
there's actually a special meaning to the `assets` folder in dash apps. They are mainly to hold `.css` files used for styling and the dash framework automatically loads styles from that folder so try not to place `.py` files here. You can place constants in a constants folder. or just in root since its going to be used everywhere

_Originally posted by @t-cheepeng in https://github.com/t-cheepeng/time-tracker-visualizer/pull/1#discussion_r652277769_

**Comment by garylyp** [comment]
Ohhh oh i see okay understood

**Comment by t-cheepeng** [comment]
Close as per comment in https://github.com/t-cheepeng/time-tracker-visualizer/pull/3#issuecomment-872882057
